
#ifndef __CL_ERROR__
#define __CL_ERROR__

enum ClError {
    UNDEFINED,
    OPEN_CL_ERROR,
    NO_PLATFORM,
    NO_DEVICE,
    KERNEL_SIZE_NOT_SET,
    KERNEL_SET_ARG_ERROR,
    KERNEL_EXEC_ERROR,
    INTER_DEVICE_COPY_ERROR,
    OUT_OF_RESOURCES,
    FILE_READ_ERROR,
    FILE_WRITE_ERROR,
    INCORRECT_KERNEL_FILE,
    INCORRECT_DATA_GENERATOR_FILE,
    NO_KERNEL_IN_COMPARATOR
};

#endif

